---
- name: Check for firewall rules
    ansible.builtin.script: firewall-cmd --list-all
    register: firewall_rules
    when: ansible_distribution == 'CentOS'
- name: Print firewall rules
    debug:
      msg: "{{ firewall_rules.stdout }}"
    when: firewall_rules is defined
