---
- name: Check service status (on/off)
  hosts: linux

  tasks:
  - name: Get service status
    ansible.builtin.service_facts:
    
  - name: Show service status
    ansible.builtin.debug:
      msg: "L'état de ufw est : {{ ansible_facts.services['ufw'].state }}"
