---
- name: Check service status (on/off)
  hosts: linux

  tasks:
  - name: Get service status
    command: systemctl status "{{ item }}"
    with_items:
    - ufw
    register: result
    ignore_errors: yes

  - name: Print result
    debug:
     var: result
