---
- name: Check service status (on/off)
  hosts: linux
  become: true

  tasks:
  - name: Get ufw status using command
    ansible.builtin.command:
      cmd: ufw status
    register: ufw_status

  - name: Show ufw status
    ansible.builtin.debug:
      msg: "L'état de ufw est : {{ ufw_status.stdout }}"
