---
- name: Check service status (on/off)
  hosts: linux
  become: true

  tasks:
  - name: Check if service is active
    ansible.builtin.systemd:
      name: ufw
      state: started
    register: service_status

  - name: Show service status
    ansible.builtin.debug:
      msg: "L'état de ufw est : {{ 'active' if service_status.status.ActiveState == 'active' else 'inactive' }}"
