---
- name: Check service status (on/off)
  hosts: linux

  tasks:
  - name: Get service status
  command: systemctl status "{{ item }}"
  with_items:
  - ufw
  - firewalld
  - sshd
  register: result

  - name: Print result
    debug:
     var: result
