---
- name: Windows Test
  hosts: windows

  tasks:
    - name: Execute ipconfig
      win_command: ipconfig
      register: ipconfig_output

    - name: Display ipconfig output
      debug:
        var: ipconfig_output.stdout_lines

